version: '3'
services:
  app:
    #app_goの中にあるDockerfileの読み込み
    build: ./app_go
    container_name: "api-golang"
    tty: true
    ports:
      - "9999:9999"
    #ホストのディレクトリをコンテナにマウント
    #volumes:
    #  - .:/go/src/app
  